name: getting started with github actions

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-on-windows:
    runs-on: windows-latest
    steps:
      - name: Step 1 - Log the pre-build disk space
        run: dir

      - name: Step 2 - Checkout the main GitHub Branch
        uses: actions/checkout@v3

      - name: Step 3 - Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Step 4 - Build your own Jakarta web app with Maven
        run: echo mvn -B package --file pom.xml

      - name: Step 5 - Check windows execution policy
        run: |
          echo Here is the windows execution policy 
          Get-ExecutionPolicy

      - name: Step 6 - List windows environment variables
        run: echo $env:Path

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Log the pre-build disk space
        run: df

      - name: Step 2 - Checkout the main GitHub Branch
        uses: actions/checkout@v3

      - name: Step 3 - Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Step 4 - Build your own web app with Maven
        run: echo mvn -B package --file pom.xml

      - name: Step 5 - Build your native Android App
        run: |
          echo Here is the ANDROID_SDK_ROOT
          echo $ANDROID_SDK_ROOT

      - name: Step 6 - Build the native Android App
        run: |
          echo the SELENIUM_JAR_PATH
          echo $SELENIUM_JAR_PATH

      - name: Step 7 - Log build tool versions
        run: |
          git --version
          mvn --version
          ant -version
          gradle --version

      - name: Step 8 - Log the post build disk space
        run: df
